all: q4 q5 q8 q9 q13 q14

q4: q4.c
	gcc q4.c -o q4

q5: q5.c
	gcc q5.c -o q5

q8: q8.c
	gcc q8.c -o q8

q9: q9.c
	gcc q9.c -o q9

q13: q13.c
	gcc q13.c -o q13

q14: q14.c
	gcc q14.c -o q14

clean:
	rm q4 q5 q8 q9 q13 q14
